### ISSUE TITLE
C++ testing

### ISSUE THREAD

**Issue by mr-c** [nemequ/simde#56] opened 2019-12-13 12:44 UTC
a tracking issue to remind us to develop (autogenerated) c++ tests and execute them in Travis CI / appveyor

**Comment by nemequ** [comment] 2019-12-14 01:03
It should be possible to just copy each C test case to a C++ file, then compile the C++ versions into a `run-tests-cpp`.

Dealing with include directories could complicate things... that could be fixed with -I... but that would complicate tooling; right now you can just open up a file and the editor can find everything straight away, which I quite like.

I have no problem tweaking the test cases so they'll compile in both C and C++, though.

**Comment by nemequ** [comment] 2019-12-20 03:20
Working on this in the wip/c++-tsets branch.

**Comment by nemequ** [comment] 2020-01-09 21:15
The wip/meson branch has working C++ tests.  I just need to port simd-js over (x86 and arm are finished) and port CI (including CodeCov) over and it can be merged.

**Comment by mr-c** [comment] 2020-01-10 08:17
@nemequ Thanks for the update. As always, I really appreciate your work!

**Comment by nemequ** [comment] 2020-01-20 07:52
This just landed (finally!) along with a bunch of other improvements to the testing architecture, including that emscripten now actually runs the tests, so we can start adding WASM implementations.

For now I've made building and running the C++ tests optional, and off by default.  You can enable them with the cmake BUILD_CPP_TESTS option (pass -DBUILD_CPP_TESTS=ON to cmake if you're using the command line).

They will be enabled on CI for all compilers except for PGI and ICC, which break in C++ mode for now.  Resolving #72 should fix PGI, and there is a good chance it will fix ICC, too.  Once they are working in C++ I'll probably remove the ability to disable the tests in CMake.

Meanwhile, I plan to start going through some of the build logs soonish to see if I spot any interesting new warnings.

**Comment by mr-c** [comment] 2020-01-20 07:53
Awesome, thank you very much @nemequ !

**Comment by mr-c** [comment] 2020-01-20 15:29
FYI, building without `-DBUILD_CPP_TESTS=ON` under Ubuntu Eoan causes the following

```
/usr/lib/ccache/cc  -fopenmp-simd -g  -rdynamic CMakeFiles/run-tests.dir/run-tests.c.o CMakeFiles/run-tests.dir/x86/test-x86.c.o CMakeFiles/run-tests.dir/arm/neon/test-neon.c.o CMakeFiles/run-tests.dir/arm/test-arm.c.o  -o run-tests libmunit.a libsimde-test-native.a libsimde-test-emul.a 
/usr/bin/ld: libsimde-test-native.a(sse.c.o): in function `test_simde_mm_cvtt_ps2pi':
/home/michael/src/simde/test/x86/sse.c:2334: undefined reference to `truncf'
```
Full log at https://gist.github.com/mr-c/a8e0ef256e4398ab866dcac5f83125ac

**Comment by mr-c** [comment] 2020-01-20 16:15
and the `add_test` cmake calls are missing, so the MS Windows build fails..

**Comment by mr-c** [comment] 2020-01-20 16:53
re-adding `add_test` results in the following test failures on Travis with MS Windows

- [ ] /x86/mmx/mm_andnot_si64/emul/c
- [ ] /x86/mmx/mm_xor_si64/emul/c
- [ ] /x86/mmx/mm_andnot_si64/emul/cpp
- [ ] /x86/mmx/mm_xor_si64/emul/cpp 
- [ ] /x86/sse/mm_cvtps_pi16/native/c
- [ ] /x86/sse/mm_cvtps_pi8/native/c
- [ ] /x86/sse/mm_cvtt_ps2pi/native/c
- [ ] /x86/sse/mm_cvttss_si64/native/c 
- [ ] /x86/sse/mm_cvtps_pi16/native/cpp 
- [ ] /x86/sse/mm_cvtps_pi8/native/cpp
- [ ] /x86/sse/mm_cvtt_ps2pi/native/cpp 
- [ ] /x86/sse/mm_cvttss_si64/native/cpp
- [ ] /x86/sse2/mm_and_pd/native/c 
- [ ] /x86/sse2/mm_cmpeq_sd/native/c 
- [ ] /x86/sse2/mm_cvttpd_pi32/native/c 
- [ ] /x86/sse2/mm_xor_pd/native/c 
- [ ] /x86/sse2/mm_and_pd/emul/c 
- [ ] /x86/sse2/mm_xor_pd/emul/c 

https://travis-ci.org/nemequ/simde/jobs/639556407

I see the list from https://github.com/nemequ/simde/issues/69 is here as well..

Similar list of tests fail on AppVeyor: https://ci.appveyor.com/project/quixdb/simde/builds/30238664/job/otipgvf4s283bsis

**Comment by nemequ** [comment] 2020-01-20 21:22
Okay, so this is going to require some major changes.  The good news is most of it was going to have to be done anyways for #72 (though I'd planned to do it in a slightly different way).

It's not the C++ stuff that broke this, but using int_fast32_t (which will be 64 bits on x86_64) in the implementation while still using int32_t in the test.  The problem was just undetected since the tests weren't actually running on Windows (excellent catch, by the way).

The problem is that SIMDe relies extensively on type-punning through unions.  For most compilers there is the `may_alias` attribute to tell the compiler that we're doing this, but not MSVC.  MSVC is usually much less aggressive about type-punning optimizations so I didn't think it would be a problem, but apparently there are some situations where it is.

The solution is to just use memcpy instead of type punning through the union.  The API will look kind of like the NEON vreinterpret functions, but we should be able to get away with two functions per type.  So `simde_mm_andnot_si64` might look something like:

```c
SIMDE__FUNCTION_ATTRIBUTES
simde__m64
simde_mm_andnot_si64 (simde__m64 a, simde__m64 b) {
#if defined(SIMDE_MMX_NATIVE)
  return _mm_andnot_si64(a.n, b.n);
#else
  simde__m64_priv a_ = simde__m64_to_priv(a);
  simde__m64_priv b_ = simde__m64_to_priv(a);
  simde__m64_priv r;

#if defined(SIMDE_MMX_NEON)
  r_.neon_i32 = vbic_s32(b.neon_i32, a.neon_i32);
#elif defined(SIMDE_VECTOR_SUBSCRIPT_OPS)
  r_.i32f = ~a_.i32f & b_.i32f;
#else
  SIMDE__VECTORIZE
  for (size_t i = 0 ; i < (sizeof(r) / sizeof(r_[0])) ; i++) {
    r_[i] = ~(a_[i]) & b_[i];
  }
#endif

  return simde__m64_from_priv(r);
#endif
}
```

`simde__m64_priv` would be what is currently `simde__m64`, and `simde__m64` would be a typedef to `__m64`, a type from some other ISA extension (e.g., for NEON, `int32x2_t`), a GCC-style vector (in this case, probably `int_fast32_t __attribute__((__vector_size__(8)))`), or for full portability something like `struct { int_fast32_t v[8 / sizeof(int_fast32_t)]; }`.

The conversion functions would probably be something like

```c
simde__m64_priv simde__m64_to_priv(simde__m64 v) {
  simde__m64_priv r;
  memcpy(&r, &v, sizeof(r));
  return r;
}

simde__m64 simde__m64_from_priv(simde__m64_priv v) {
  simde__m64 r;
  memcpy(&r, &v, sizeof(r));
  return r;
}
```

All compilers are very good at optimizing this away.  Actually, I think they'll have an easier time of it than punning through the union, which was my initial reason for wanting to do #72.

Note that I haven't decided on the naming convention (`simde__m64_priv`, `simde__m64_to/from_priv`, etc.).  I'm very much open to suggestions here.

I'm going to close this back up since it's not really about C++, we should move the conversation to #72.

Meanwhile, do you mind if I merge your arm32_cpp patches and just add windows to the allowed failures for now?

**Closed by nemequ** 2020-01-20 21:22 UTC
Labels: enhancement

**Comment by mr-c** [comment] 2020-01-20 21:36
Thanks for the explanation!

> Meanwhile, do you mind if I merge your arm32_cpp patches and just add windows to the allowed failures for now?

Sure!

**Comment by mr-c** [comment] 2020-01-20 21:41
It would be really great if these explanations were captured in the form of Architecture Decision Records https://github.com/joelparkerhenderson/architecture_decision_record

I'm sure other developers/users will want to know more about the thinking and experience behind the design decisions.
