### ISSUE TITLE
Add Galois Field New Instructions

### ISSUE THREAD

**Issue by rosbif** [nemequ/simde#169] opened 2020-04-09 08:25 UTC
I would like to add GFNI to SIMDe.

When I first looked at GFNI I thought that these intrinsics were useless for me as many are hardwired for the (IMHO stupid) reduction polynomial x^8 + x^4 + x^3 + x + 1 (0x11B) probable inherited from AES, whereas I need 0x11D and 0x187.
(I say stupid because, although irreducible, their polynomial is not primitive. This causes problems for some use cases.)
Yesterday I decided to have a closer look at these intrinsics and found out how I could use them profitably.

According to the IIG some intrinsics depend on GFNI + AVX512F and others on GFNI + AVX512VL.
I figure I should put them in gfni.[hc].
What do you think?
Would you accept patches?

https://software.intel.com/sites/landingpage/IntrinsicsGuide/#avx512techs=GFNI

Also requires AVX512F:
 
 - [ ] _mm512_gf2p8affine_epi64_epi8
 - [ ] _mm512_mask_gf2p8affine_epi64_epi8
 - [ ] _mm512_maskz_gf2p8affine_epi64_epi8
 - [ ] _mm512_gf2p8affineinv_epi64_epi8
 - [ ] _mm512_mask_gf2p8affineinv_epi64_epi8
 - [ ] _mm512_maskz_gf2p8affineinv_epi64_epi8
 - [ ] _mm512_gf2p8mul_epi8
 - [ ] _mm512_mask_gf2p8mul_epi8
 - [ ] _mm512_maskz_gf2p8mul_epi8
 
Also requires AVX512VL:
 
 - [ ] _mm_gf2p8affine_epi64_epi8
 - [ ] _mm_mask_gf2p8affine_epi64_epi8
 - [ ] _mm_maskz_gf2p8affine_epi64_epi8
 - [ ] _mm256_gf2p8affine_epi64_epi8
 - [ ] _mm256_mask_gf2p8affine_epi64_epi8
 - [ ] _mm256_maskz_gf2p8affine_epi64_epi8
 - [ ] _mm_gf2p8affineinv_epi64_epi8
 - [ ] _mm_mask_gf2p8affineinv_epi64_epi8
 - [ ] _mm_maskz_gf2p8affineinv_epi64_epi8
 - [ ] _mm256_gf2p8affineinv_epi64_epi8
 - [ ] _mm256_mask_gf2p8affineinv_epi64_epi8
 - [ ] _mm256_maskz_gf2p8affineinv_epi64_epi8
 - [ ] _mm_gf2p8mul_epi8
 - [ ] _mm_mask_gf2p8mul_epi8
 - [ ] _mm_maskz_gf2p8mul_epi8
 - [ ] _mm256_gf2p8mul_epi8
 - [ ] _mm256_mask_gf2p8mul_epi8
 - [ ] _mm256_maskz_gf2p8mul_epi8

**Comment by nemequ** [comment] 2020-04-09 15:19
Yeah, I'd accept them.  gfci.[hc] makes sense to me.

> Yesterday I decided to have a closer look at these intrinsics and found out how I could use them profitably.

Nice.  I haven't actually looked at them yet, but I'm glad to hear they're useful for something other than GCM.

**Comment by rosbif** [comment] 2020-04-22 04:15
@nemequ: I notice that you have generated a list of intrinsics for all the other AVX512* classes.
I imagine that you have an automatic way of doing this.
If so, please would you do the same for GFNI (under "Other" in the IIG)?
TIA.

**Comment by nemequ** [comment] 2020-04-22 06:19
Sure.  I'm not sure if this will show up as a list on the summary page (I've only tried with the list in the first comment), but if not I can always open up a new issue, or if you want to paste it into your initial comment here is the markdown: https://paste.centos.org/view/69c4e111 

Also requires AVX512F:

 - [ ] _mm512_gf2p8affine_epi64_epi8
 - [ ] _mm512_mask_gf2p8affine_epi64_epi8
 - [ ] _mm512_maskz_gf2p8affine_epi64_epi8
 - [ ] _mm512_gf2p8affineinv_epi64_epi8
 - [ ] _mm512_mask_gf2p8affineinv_epi64_epi8
 - [ ] _mm512_maskz_gf2p8affineinv_epi64_epi8
 - [ ] _mm512_gf2p8mul_epi8
 - [ ] _mm512_mask_gf2p8mul_epi8
 - [ ] _mm512_maskz_gf2p8mul_epi8

Also requires AVX512VL:

 - [ ] _mm_gf2p8affine_epi64_epi8
 - [ ] _mm_mask_gf2p8affine_epi64_epi8
 - [ ] _mm_maskz_gf2p8affine_epi64_epi8
 - [ ] _mm256_gf2p8affine_epi64_epi8
 - [ ] _mm256_mask_gf2p8affine_epi64_epi8
 - [ ] _mm256_maskz_gf2p8affine_epi64_epi8
 - [ ] _mm_gf2p8affineinv_epi64_epi8
 - [ ] _mm_mask_gf2p8affineinv_epi64_epi8
 - [ ] _mm_maskz_gf2p8affineinv_epi64_epi8
 - [ ] _mm256_gf2p8affineinv_epi64_epi8
 - [ ] _mm256_mask_gf2p8affineinv_epi64_epi8
 - [ ] _mm256_maskz_gf2p8affineinv_epi64_epi8
 - [ ] _mm_gf2p8mul_epi8
 - [ ] _mm_mask_gf2p8mul_epi8
 - [ ] _mm_maskz_gf2p8mul_epi8
 - [ ] _mm256_gf2p8mul_epi8
 - [ ] _mm256_mask_gf2p8mul_epi8
 - [ ] _mm256_maskz_gf2p8mul_epi8

**Comment by mr-c** [comment] 2020-04-22 09:31
@nemequ @rosbif I've added the list to the original comment, as that is required for the `0 of 27` to show up in the issues overview

**Comment by rosbif** [comment] 2020-04-25 07:06
I have nearly finished the GFNI intrinsics but I have two problems :-(

First: a clang bug which, I imagine, will cause your tests to fail.
Clang version 10.0.0-4ubuntu1 from Ubuntu 20.04 LTS gives the following error:
In file included from decode_rs_ccsdsCM.c:198:
./../../simde/simde/x86/gfni.h:61:12: error: argument to '__builtin_ia32_vgf2p8affineqb_v16qi' must be a constant integer
    return _mm_gf2p8affine_epi64_epi8(x, A, b);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/lib/llvm-10/lib/clang/10.0.0/include/gfniintrin.h:64:12: note: expanded from macro '_mm_gf2p8affine_epi64_epi8'
  (__m128i)__builtin_ia32_vgf2p8affineqb_v16qi((__v16qi)(__m128i)(A),             \
           ^
This is wrong: the IIG doesn't specify a compile-time constant and the code compiles, runs and works with gcc.
A similar error occurs with all the gf2p8affine intrinsics.
Do you know of a version of clang with this bug corrected?
Otherwise do you have a contact to report it?

Second: code to generate the inverse necessary for the gf2p8affineinv intrinsics is complicated and very slow.
Would you accept a 256-byte LUT (in static const)?

**Comment by nemequ** [comment] 2020-04-25 09:32
> This is wrong: the IIG doesn't specify a compile-time constant and the code compiles, runs and works with gcc.

Sadly I think clang is right here.  The [SDM](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf) is pretty clear that the parameter is encoded into an immediate byte of `VGF2P8AFFINEQB` (Volume 2A, 3-444 / page 1036).  Actually, looking a bit more closely at the IIG, it does say "… b is a constant immediate byte".

GCC tends to be a bit more lax about this, but it will generate [a similar error](https://godbolt.org/z/BmZLKZ).  I haven't done much experimenting, but I believe GCC allows you to use any compile-time constant (i.e., `__builtin_constant_p`), whereas clang infuriatingly requires an integer constant expression.

> code to generate the inverse necessary for the gf2p8affineinv intrinsics is complicated and very slow. Would you accept a 256-byte LUT (in static const)?

Yeah, I think that would be okay.  I don't want to make a habit of it, but the occasional LUT seems reasonable.  I'm not sure how exactly you're using it, but maybe `_mm256_shuffle_epi8` could be useful?

> Third: the pseudo-code algorithm for the gf2p8affine intrinsics in the IIG is incredibly slow.
I have a much more efficient algorithm for the matrix multiplication but it bears no ressemblance to the Intel pseudo-code. Is this a problem?

Not even a little.  Lots of the pseudo-code would perform abysmally.  As long as your implementation provides the same results given the same inputs it's completely fine.

> On the subject of pseudo-code, do you know if there is pseudo-code somewhere for the NEON intrinsics (apart from deduction from Victoria's excellent NEON2SSE) ?

The [NEON Intrinsics Reference](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics) contains links to the relevant instruction in the [Arm A64 Instruction Set Architecture](https://developer.arm.com/docs/ddi0596/e).  It's not as nice as Intel's (it's kind of like if the IIG linked to the SDM instead of having their own pseudo-code), but it's the best I'm aware of.

**Comment by rosbif** [comment] 2020-04-25 12:19
Thank you, Evan, for your quick and thorough reply.

> > This is wrong: the IIG doesn't specify a compile-time constant and the code compiles, runs and works with gcc.
> 
> Sadly I think clang is right here. The [SDM](https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf) is pretty clear that the parameter is encoded into an immediate byte of `VGF2P8AFFINEQB` (Volume 2A, 3-444 / page 1036). Actually, looking a bit more closely at the IIG, it does say "… b is a constant immediate byte".
> 
> GCC tends to be a bit more lax about this, but it will generate [a similar error](https://godbolt.org/z/BmZLKZ). I haven't done much experimenting, but I believe GCC allows you to use any compile-time constant (i.e., `__builtin_constant_p`), whereas clang infuriatingly requires an integer constant expression.
> 

Sorry, it seems that you are right (again).
Generally Intel misuses const in the arguments to point this out. I didn't look closely enough at the text.
So I shall have to use a macro for the native case.
Incidentally I can't see the use of the b argument: it is a scalar but to be of any use it should be a vector.

> > code to generate the inverse necessary for the gf2p8affineinv intrinsics is complicated and very slow. Would you accept a 256-byte LUT (in static const)?
> 
> Yeah, I think that would be okay. I don't want to make a habit of it, but the occasional LUT seems reasonable. I'm not sure how exactly you're using it, but maybe `_mm256_shuffle_epi8` could be useful?
> 

I am a great fan of the shuffle_epi8 intrinsics which can be used as a 4-bit LUT: in SSE and AVX (and NEON) I use two shuffles to replace an 8-bit LUT for GF multiplication since a * (b + c) = a * b + a * c.
However in this case I am pretty certain that two 4-bit LUTs cannot be used to replace an 8-bit LUT.

**Comment by rosbif** [comment] 2020-04-25 14:48
More questions :-(

I propose to simulate the gf2p8affine intrinsics in SSE.
The best solution I have found uses SSE4.1 (for blendv).
At a very slight extra cost in execution time I could reduce the requirement to SSSE3 (for shuffle).
I could even supply both (plus maybe an AVX2 version).
What would you prefer?

My mask versions currently require looping byte by byte to apply the mask and will be slow.
AVX512 has movm_epi8 intrinsics to transform a mask into 0x00/0xFF bytes which would avoid looping.
Many systems have AVX512 without GFNI. Is it worth providing an AVX512 fallback?
Do you know of a fast way to transform a mask into bytes using SSE or AVX?

Unfortunately my affineinv versions also require looping byte by byte to apply my inverse LUT so they will be slow too.

**Comment by mr-c** [comment] 2020-04-25 15:01
Implementations using any level of CPU features are welcome!

**Comment by nemequ** [comment] 2020-04-26 04:10
> Implementations using any level of CPU features are welcome!

Indeed.  We'll definitely take whatever you're willing to provide.

The optimal solution would be both, and just use the preprocessor to switch between them.  It sounds like you've already written the code, so hopefully that wouldn't be too difficult, but if it is either one would be acceptable.  SSE4.1 has pretty good market penetration at this point; the [Steam Hardware Survey](https://store.steampowered.com/hwsurvey) puts it at 97.88% compared to 98.56% for SSSE3, though of course gamers are a pretty biased sample.

> Many systems have AVX512 without GFNI. Is it worth providing an AVX512 fallback?

I think so.  ICL is still pretty rare, and I've actually been seeing a fair amount of interest lately (such as [here](https://branchfree.org/2019/05/29/why-ice-lake-is-important-a-bit-bashers-perspective/) and [here](http://www.0x80.pl/articles/avx512-galois-field-for-bit-shuffling.html)) in using GFNI… it might prove to be quite popular, so a fast implementation would be quite valuable.

> Do you know of a fast way to transform a mask into bytes using SSE or AVX?

I haven't really played with it yet, but I've been thinking that you could broadcast the mask to a vector, left shift by lane # bits, then arithmetic right shift by the width of the lane.  I wish I could think of a good way to generate a vector where each lane contains the lane number, but I can't think of anything faster than just `_mm*_set_*` :(

There is a `simde__m512i_from_mmask16` function in avx512f.h to do it, though it's not exactly fast right now; I think the best thing to do would be to either use that or add versions for other mask types, that way if we do figure out a good way to do it in the future everyone can benefit from the optimization.

**Comment by rosbif** [comment] 2020-04-26 13:33
Thank you, Evan, for your reply and for the mask hint.
I am just finishing off the test vectors.
Following the principle "release early, release often" I shall submit a set with SSE4.1 fallbacks first for your approval (or disapproval).
If you accept it I shall subsequently add other optimizations and fallbacks.
I hope this is OK.

**Comment by nemequ** [comment] 2020-04-27 03:39
> I hope this is OK.

Absolutely, I think that's the right move.  Thanks again for working on this, it's looking really good :)

What are you using to test this?  Do you have GFNI hardware?  If not and you're not already aware of it, you might want to grab a copy of Intel's [Software Development Emulator](https://software.intel.com/en-us/articles/intel-software-development-emulator/).  It's slow, but it's a good way to test functions which you don't have hardware for.  There is [a quick blurb](https://github.com/nemequ/simde/wiki/Development-Environment#x86--x86_64) about it on the wiki; in this case I believe '-mavx512vl -mgfni' should do the trick.

Since it's so painfully slow, you might want to only run the GFNI tests; you can do that with `./run-tests /x86/gfni` (well, `path/to/sde/sde64 -- ./run-tests /x86/gfni`).

**Comment by rosbif** [comment] 2020-04-27 06:26
Yes, I do exactly that.
Unfortunately run-tests doesn't pick up nearly all the errors (and warnings) found by the test suite executed after a PR.
I naively thought: run-tests OK; job done.
I don't have GFNI (or even AVX512) hardware. My current hardware is very old: I do most of my work on an old laptop with just SSE4.2. I also have a Haswell desktop: the first with AVX2.
I am planning to upgrade when Intel ship Ice Lake or Tiger Lake low- to mid-end desktop processors.
While they should have AVX512 I am not certain that Ice Lake will have GFNI.
Meanwhile I also occasionally use the Intel SDE for my own internal tests but the execution time for a complete series of tests passes from a few minutes to several hours :-(
Do you know if it is possible to get the SDE to estimate the run time on real hardware?

**Comment by mr-c** [comment] 2020-04-27 07:02
> Unfortunately run-tests doesn't pick up nearly all the errors (and warnings) found by the test suite executed after a PR.

This is to be expected. The test suite runs on many different hardware types, OSs, and compilers. We could probably set up some Docker containers to replicate some more of the tests locally, so I've opened https://github.com/nemequ/simde/issues/242 to track that.

>I am planning to upgrade when Intel ship Ice Lake or Tiger Lake low- to mid-end desktop processors.
While they should have AVX512 I am not certain that Ice Lake will have GFNI.

Wikipedia says yes, so here is hoping! https://en.wikipedia.org/wiki/Ice_Lake_(microprocessor)
This is backed up by https://software.intel.com/sites/default/files/managed/39/c5/325462-sdm-vol-1-2abcd-3abcd.pdf#page=115

Thanks again for your contributions! We'll get these last bugs ironed out and this merged soon, I'm sure.

**Comment by nemequ** [comment] 2020-04-28 00:03
> Yes, I do exactly that.
> Unfortunately run-tests doesn't pick up nearly all the errors (and warnings) found by the test suite executed after a PR.
> I don't have GFNI (or even AVX512) hardware. My current hardware is very old: 

Yeah, CI is pretty aggressive about warnings.  It helps if you add `-Wall -Wextra -Werror` to your flags, but even then MSVC tends to pick up some more stuff GCC and clang miss.

> I naively thought: run-tests OK; job done.I do most of my work on an old laptop with just SSE4.2. I also have a Haswell desktop: the first with AVX2.
> I am planning to upgrade when Intel ship Ice Lake or Tiger Lake low- to mid-end desktop processors.
> While they should have AVX512 I am not certain that Ice Lake will have GFNI.
> Meanwhile I also occasionally use the Intel SDE for my own internal tests but the execution time for a complete series of tests passes from a few minutes to several hours :-(

Yeah, it's really slow :(.  `./run-tests /x86/gfni` should be a huge help.

> Do you know if it is possible to get the SDE to estimate the run time on real hardware?

Not AFAIK, but you could use [llvm-mca](https://www.llvm.org/docs/CommandGuide/llvm-mca.html).  It's knd of like the old (EOL) [IACA](https://software.intel.com/en-us/articles/intel-architecture-code-analyzer/).  Just create a file like

```c
#include "simde/x86/gfni.h"

simde__m128i foo(simde__m128i x, simde__m128i A, int b) {
  return _mm_gf2p8affine_epi64_epi8(x, A, b);
}
```

Then do something like `clang foo.c -O3 -DSIMDE_ENABLE_OPENMP -fopenmp-simd -march=native -target x86_64-unknown-unknown -S -o - | llvm-mca -mcpu=native`.

If you just want to see how expensive one or two operations is, [uops.info](https://uops.info/) is definitely the place to go.

**Comment by mr-c** [comment] 2020-04-28 11:48
https://github.com/nemequ/simde/commit/bf7fcd45dce56cd6f381c3d886476b3954f61d6b from https://github.com/nemequ/simde/tree/wip/gfni is passing the tests

I'll let @nemequ do any other cleanups he wishes and to merge

I have a hypothesis about why my ICC dockerfile caught some problems but not others: I only have AVX2, while the servers that Travis CI uses has AVX512{cd,bw,dq,f,vl,vnni}, so different code paths were tested.

**Comment by rosbif** [comment] 2020-04-28 12:44
> I have a hypothesis about why my ICC dockerfile caught some problems but not others: I only have AVX2, while the servers that Travis CI uses has AVX512{cd,bw,dq,f,vl,vnni}, so different code paths were tested.

This sounds highly plausible: let me know if I can help.

While I appreciate that to actually run all tests on all code paths would be very time consuming, couldn't run-tests at least compile-test all code paths (different pure C/MMX/SSE/AVX/AVX512/GFNI levels)?
This would pick up the stupid errors in my PR and subsequent commits.

Also as you are really serious about big-endian support it would be useful to have portable macros or functions for 16-bit, 32-bit and 64-bit byte swaps.
Not being sure of where the endian problem was, I used __builtin_bswap64 for a quick test but this is probably not portable outside gcc, clang and (maybe) icc.

**Comment by mr-c** [comment] 2020-04-28 15:47
> While I appreciate that to actually run all tests on all code paths would be very time consuming, couldn't run-tests at least compile-test all code paths (different pure C/MMX/SSE/AVX/AVX512/GFNI levels)?
We have this, but with gcc and not icc :-P https://github.com/nemequ/simde/runs/625771226

**Comment by rosbif** [comment] 2020-04-28 15:59
Yes, that would be very useful to avoid you seeing my silly errors.
Can I run it locally before committing my code?
Or at least after pushing to my fork but without generating a PR?

Also can I run the complete battery of tests without generating a PR?

**Comment by mr-c** [comment] 2020-04-28 16:25
Well, you need to run it on a processor with all the various SIMD capabilities. So locally I can only replicate up to -mavx2 ; probably something similar to you

**Comment by mr-c** [comment] 2020-04-28 16:27
> Or at least after pushing to my fork but without generating a PR?

I think @nemequ invited you to the repository. So yes, just push a branch to this repository and then check the commit, like bf7fcd4 from https://github.com/nemequ/simde/tree/wip/gfni

**Comment by rosbif** [comment] 2020-04-29 05:05
I don't feel happy about pushing to nemequ if that is what you mean.
I am pretty much a newbie to git and even more so to GitHub and I don't yet feel I understand them sufficiently to not do something stupid.
Or do you just mean pushing to my GitHub fork?

To continue my work I have two main intentions:
- to add some NEON intrinsics (and make some corrections as SIMDe NEON is currently virtually unusable) but Evan asked me to hold off.
- to add some more fallbacks and optimizations to GFNI but I really would like to get GFNI merged into mainline first.

The more we wait, the harder it will be to merge.
If this is prevented by the icc failures then why not just recommend not using icc (or at least not using icc to vectorize) as Michael has confirmed my idea that icc is crap by showing that by removing SIMDE__VECTORIZE the gf2p8mul errors magically disappear?
Or just avoid enabling OpenMP vectorization in the icc compilation flags?

**Comment by nemequ** [comment] 2020-04-30 01:27
> I don't feel happy about pushing to nemequ if that is what you mean.
> I am pretty much a newbie to git and even more so to GitHub and I don't yet feel I understand them sufficiently to not do something stupid.

Okay, I don't want to push you to do anything you're not comfortable with.  It sounds like you're mostly done with GFNI anyways, and I just need to rebase it, review it, and merge it.

> To continue my work I have two main intentions:
> 
>     * to add some NEON intrinsics (and make some corrections as SIMDe NEON is currently virtually unusable) but Evan asked me to hold off.

Sorry, I'll try to wrap this up soon.

> The more we wait, the harder it will be to merge.

If this drags on I'll handle periodic rebasing.  It seems like it's almost done, though.

> If this is prevented by the icc failures then why not just recommend not using icc (or at least not using icc to vectorize) as Michael has confirmed my idea that icc is crap by showing that by removing SIMDE__VECTORIZE the gf2p8mul errors magically disappear?

Unfortunately ICC is a somewhat important target.  It's used for a lot of HPC stuff since it tends to result in faster executables.  As I mentioned in the other issue, the issue has been reported to Intel, but I have no way of knowing when (or if) they'll get around to fixing it.

> As Victoria's excellent NEON2SSE is virtually complete (apart from AArch64 extensions), isn't there a way to combine the two efforts rather than duplicating them?
> (There may be a license problem but couldn't it be ironed out?)

Yes, it's a licensing issue.  https://github.com/intel/ARM_NEON_2_x86_SSE/issues/4

My understanding is that it would require a couple approvals as well as muliple legal reviews.  Unfortunately, I suspect it would be less work to just rewrite it.  We can still look at it for inspiration if we're not sure what the equivalent functions would be, we just can't copy it.  That said, if you'd be interested in contacting Intel about the issue I'd certainly be supportive.

**Comment by rosbif** [comment] 2020-05-02 12:47
> > Do you know of a fast way to transform a mask into bytes using SSE or AVX?
> 
> I haven't really played with it yet, but I've been thinking that you could broadcast the mask to a vector, left shift by lane # bits, then arithmetic right shift by the width of the lane. I wish I could think of a good way to generate a vector where each lane contains the lane number, but I can't think of anything faster than just `_mm*_set_*` :(
> 
> There is a `simde__m512i_from_mmask16` function in avx512f.h to do it, though it's not exactly fast right now; I think the best thing to do would be to either use that or add versions for other mask types, that way if we do figure out a good way to do it in the future everyone can benefit from the optimization.
> 

I have found a way to do a 16-bit mask -> 0x00/0xFF bytes  transformation in SSSE3 with seven in line intrinsics, three of which are to generate constants.
I am virtually certain that a 32-bit mask -> 0x00/0xFF in AVX2 will also work with seven intrinsics.
(The task was somewhat complicated by the fact that there are no 8-bit shifts or multiplies in SSE and AVX.)

I shall push the modifications once you have merged my other pending avx512*.h modifications.

**Closed** 2020-05-02 16:08 UTC
Labels: enhancement, instruction-set-support

**Comment by nemequ** [comment] 2020-05-02 17:07
I merged this into master, but I'm running into a problem on GCC where if the immediate mode argument is negative  GCC will error:

```
../test/x86/gfni.c: In function ‘test_simde_mm256_gf2p8affine_epi64_epi8’:
../simde/x86/gfni.h:144:55: error: the last argument must be an 8-bit immediate
  144 |   #define simde_mm256_gf2p8affine_epi64_epi8(x, A, b) _mm256_gf2p8affine_epi64_epi8(x, A, b)
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../test/x86/gfni.c:351:22: note: in expansion of macro ‘simde_mm256_gf2p8affine_epi64_epi8’
  351 |     simde__m256i r = simde_mm256_gf2p8affine_epi64_epi8(test_vec[i].x, test_vec[i].A, INT8_C( -60));
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm thinking I'll just regenerate the test cases with only positive values since it's not exactly something we can work around, but before I report the issue to GCC I wanted to ask if you could think of any reason why negative imm8 values wouldn't make sense?  Reading the pseudo-code in the IIG negatives seem perfectly reasonable…

**Comment by rosbif** [comment] 2020-05-02 21:33
> I'm thinking I'll just regenerate the test cases with only positive values since it's not exactly something we can work around, but before I report the issue to GCC I wanted to ask if you could think of any reason why negative imm8 values wouldn't make sense? Reading the pseudo-code in the IIG negatives seem perfectly reasonable…
> 

For the Galois field used here (GF2**8) the only valid elements are 0 to 255.
I don't know why Intel make the argument an int: it should logically be a uint8_t.
In fact a negative value is really misleading. If, for example, -1 were defined it would have the same representation as +1 since in GF arithmetic addition and subtraction are the same operation!
However the computer's representation of -1 would be equivalent to 255.
To avoid regenerating the test vectors you could just replace the current value of b with b & 0xFF: conserving the bit pattern of the 8 LSBits.
(The code only uses the 8 LSBits.)

> _Edit_: after looking at it a bit more, both positions seem reasonable. GCC is validating that the value is in [0, 255] (or probably just that `(v & 0xff) == v`), whereas ICC and clang just blindly use the least significant 8 bits. Since the argument is really an int not an int8_t (or char) a negative will generate in a lot of set bits which need to be discarded. I think I'll skip the bug report, [053ef0c](https://github.com/nemequ/simde/commit/053ef0c6977e72e1c9b33f0d81a98f30134560c9) resolves the problem in SIMDe.
> 

Both behaviours seem reasonable as only values in the range [0..255] make sense.

> That said, I do have another question: is there a reason the `simde_gf2p8inverse` LUT can't just be moved inside `simde_x_mm_gf2p8matrix_multiply_inverse_epi64_epi8`? i.e., are you planning on using it in other functions? I'd just rather not expose it like that if we don't have to.
>

In my upcoming version I shall also be using the LUT (which becomes a union) in my attempts to optimize the 256-bit version.
However I am not yet sure whether my "optimizations", which I vaguely described elsewhere, are actually faster than the LUT :-(

**Comment by nemequ** [comment] 2020-05-03 17:40
> > I'm thinking I'll just regenerate the test cases with only positive values since it's not exactly something we can work around, but before I report the issue to GCC I wanted to ask if you could think of any reason why negative imm8 values wouldn't make sense? Reading the pseudo-code in the IIG negatives seem perfectly reasonable…
> 
> For the Galois field used here (GF2**8) the only valid elements are 0 to 255.
> I don't know why Intel make the argument an int: it should logically be a uint8_t.

Oh, they do that everywhere.  grep for imm8, all those are 8-bit immediate mode arguments, and they're all ints.

In their defense, I actually played with making these (u)int8_t in SIMDe and didn't really like the result much either.  The problem is that a lot of times it's really only a few bits that you want, not all 8, but there is no uint6_t.  You end up with lots of inconsistencies.  If I were writing the API from scratch I'd do it, but the incompatibility between SIMDe and the Intel API didn't seem worth it.

> In fact a negative value is really misleading. If, for example, -1 were defined it would have the same representation as +1 since in GF arithmetic addition and subtraction are the same operation!

Interesting point, I hadn't thought of that.  And they do define the operation as adding `b` in the descriptions, so I think you're right.

In that case, I should probably go through and add checks to verify that all values are in the expected range.

> However the computer's representation of -1 would be equivalent to 255.
> To avoid regenerating the test vectors you could just replace the current value of b with b & 0xFF: conserving the bit pattern of the 8 LSBits.
> (The code only uses the 8 LSBits.)

Yep, that's basically what I did in 053ef0c6977e72e1c9b33f0d81a98f30134560c9.

> In my upcoming version I shall also be using the LUT (which becomes a union) in my attempts to optimize the 256-bit and 512-bit versios.
> And possibly also a 512-bit version with VBMI.
> But AFAICS all processors with VBMI, except Cannon Lake, already have GFNI which makes a VBMI optimization of very limited use.
> However I am not yet sure whether my "optimizations", which I vaguely described elsewhere, are actually faster than the LUT :-(
> (They load consecutive values from the the LUT and use shuffle type operations to actually perform the look-up.)

Okay, I'll leave it alone for now.  If the optimizations don't work out (or you just get too annoyed with all the restrictions, like `_mm256_shuffle_epi8` only shuffling within 128-bit lanes) we can just move it inside a function.  If they do we should probably rename it to something like `simde_x_gfni_gf2p8inverse`.  

Thanks again for all your work on this.  Hopefully it hasn't been too painful.

**Comment by mr-c** [comment] 2020-06-22 08:42
I'm so slow sometimes, I just noticed this issue was closed last month. Congratulations and many thanks @rosbif !

**Comment by rosbif** [comment] 2020-06-22 14:12
@mr-c No, it's my fault. I didn't think about closing it when all the intrinsics were covered.
