### ISSUE TITLE
NEON on SSE

### ISSUE THREAD

**Issue by rosbif** [nemequ/simde#159] opened 2020-04-06 08:06 UTC
README.md says "You can run NEON code on your x86 machine without an emulator." 
However AFAICS extremely few NEON intrinsics are currently implemented.

I have a NEON version of my code which it would be nice to run using SIMDE.
(It is tested natively and also using ARM_NEON_2_x86_SSE.)

Is there any interest in my implementing the necessary NEON instructions in SIMDE?
Do you have any guidelines for me?

**Comment by nemequ** [comment] 2020-04-06 18:13
> However AFAICS extremely few NEON intrinsics are currently implemented.

Yes.  And they need to be re-written to act more like the x86 ones.

> Is there any interest in my implementing the necessary NEON instructions in SIMDE?

Yes, absolutely.  There are a *lot* of functions, and ARM's documentation is somewhat lacking

> Do you have any guidelines for me?

Wait.  I'm working on a script to generate the NEON prototypes and scaffolding.  I've been a bit sidetracked lately, but I have enough of it done to be confident it will work at least for the vast majority of functions, I just need a little time to finish it up.

Once I'm done I'll ping you.  At that point, it should basically be the same as implementing the x86 functions.

Closing because this is basically a duplicate of #10, but feel free to keep using this if you have more questions.  Or, if you prefer, I created [a chat room for SIMDe](https://gitter.im/simd-everywhere/community) a couple days ago.

**Closed by nemequ** 2020-04-06 18:13 UTC
