### ISSUE TITLE
The build for the tests fails on gcc10

### ISSUE THREAD

**Issue by junaruga** [nemequ/simde#124] opened 2020-03-28 18:06 UTC
On the latest master branch commit: `fe43fdd6a1da24f0d6fb3f7339a3139719310729`, the unit test's `make -j` after `cmake ..` fails with gcc 10.0.1 on Fedora rawhide (= Fedora 33 = development version) by following errors. All the log is [here](https://gist.github.com/junaruga/35eebca3ffdbc607e7d99fa583b21bb6).

This command `make -j` and `./run-tests` succeed with gcc 9.2.1 on Fedora 31.
Do you have any idea to fix it? Thank you.

```
$ gcc --version
gcc (GCC) 10.0.1 20200325 (Red Hat 10.0.1-0.10)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (GCC) 10.0.1 20200325 (Red Hat 10.0.1-0.10)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

```
$ mkdir test/build
$ cd test/build
$ cmake ..
$ make -j
...
In file included from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../simde/x86/avx2.h:32,
                 from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../simde/x86/svml.h:29,
                 from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/x86/svml.c:27:
/builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../simde/x86/avx.h: In function 'simde__m256i_from_private':
/builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../simde/x86/avx.h:282:1: note: the ABI for passing parameters with 32-byte alignment has changed in GCC 4.6
  282 | simde__m256i_from_private(simde__m256i_private v) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../simde/x86/avx512bw.h:29,
                 from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/x86/avx512bw.c:25:
/builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../simde/x86/avx512f.h: In function 'simde__m512i_from_private':
/builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../simde/x86/avx512f.h:314:1: note: the ABI for passing parameters with 64-byte alignment has changed in GCC 4.6
  314 | simde__m512i_from_private(simde__m512i_private v) {
      | ^~~~~~~~~~~~~~~~~~~~~~~~~
...
```

**Comment by nemequ** [comment] 2020-03-28 21:54
That's not good, I'm glad you spotted it.

It looks like a GCC bug.  I filed a bug report, [#94385](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94385).

The notes about the ABI changing are irrelevant (I'd *love* to know how to get rid of them, though), the real problem is here:

```
during RTL pass: expand
In file included from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../test/x86/../../simde/x86/mmx.h:28,
                 from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../test/x86/../../simde/x86/sse2.h:30,
                 from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../test/x86/test-sse2.h:1,
                 from /builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/build/x86/sse.cpp:25:
/builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../test/x86/../../simde/x86/sse.h: In function 'MunitResult test_simde_mm_avg_pu16(const MunitParameter*, void*)':
/builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../test/x86/../../simde/x86/../simde-common.h:164:53: internal compiler error: in expand_PHI, at internal-fn.c:3668
  164 | #      define SIMDE__CONVERT_VECTOR(to, from) ((to) = (__extension__({ \
      |                                               ~~~~~~^~~~~~~~~~~~~~~~~~~~
  165 |            __typeof__(from) from_ = (from); \
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~        
  166 |            ((void) from_); \
      |            ~~~~~~~~~~~~~~~~~                         
  167 |            __builtin_convertvector(from_, __typeof__(to)); \
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  168 |          })))
      |          ~~~~                                        
/builddir/build/BUILD/simde-fe43fdd6a1da24f0d6fb3f7339a3139719310729/test/../test/x86/../../simde/x86/sse.h:368:3: note: in expansion of macro 'SIMDE__CONVERT_VECTOR'
  368 |   SIMDE__CONVERT_VECTOR(wa, a_.u16);
      |   ^~~~~~~~~~~~~~~~~~~~~
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
```

Here is a test case (or, [on Compiler Explorer](https://godbolt.org/z/FMbXgs)):

```c
#include <stdint.h>

typedef int32_t vec32 __attribute__((__vector_size__(16)));
typedef float vecf __attribute__((__vector_size__(16)));

vec32 foo(vecf bar) {
  return (__extension__({
    __builtin_convertvector(bar, vec32);
  }));
}
```

Using a statement expr for __builtin_convertvector is a workaround for [GCC bug #93557](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93557); if the GCC folks don't fix this before a release I can ifdef around it, using the statement expr for 9 and dropping it for 10+.

**Comment by junaruga** [comment] 2020-03-29 18:08
Thank you for checking and reporting it.
The Compiler Explorer looks very useful to check the compiler's behaviors.

Right now I applied following patch not to define `SIMDE__CONVERT_VECTOR` on gcc 10+ to pass the unit tests on the gcc 10 environment.

```
diff --git a/simde/simde-common.h b/simde/simde-common.h
index 78df1d1..b6b579b 100644
--- a/simde/simde-common.h
+++ b/simde/simde-common.h
@@ -159,7 +159,7 @@
 /* TODO: this actually works on XL C/C++ without SIMDE_VECTOR_SUBSCRIPT
    but the code needs to be refactored a bit to take advantage. */
 #  if !defined(SIMDE_NO_CONVERT_VECTOR) && defined(SIMDE_VECTOR_SUBSCRIPT)
-#    if HEDLEY_HAS_BUILTIN(__builtin_convertvector) || HEDLEY_GCC_VERSION_CHECK(9,0,0)
+#    if (HEDLEY_HAS_BUILTIN(__builtin_convertvector) || HEDLEY_GCC_VERSION_CHECK(9,0,0)) && HEDLEY_GCC_VERSION < HEDLEY_VERSION_ENCODE(10,0,0)
 /* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93557 */
 #      define SIMDE__CONVERT_VECTOR(to, from) ((to) = (__extension__({ \
            __typeof__(from) from_ = (from); \
```

**Comment by junaruga** [comment] 2020-03-29 22:24
On the latest master branch commit: `434b6272e1db863e743cc994f760274d2ecd1e8d`, applying above patch not to define `SIMDE__CONVERT_VECTOR` on gcc 10+, I faced the same kind of error on Fedora 31 s390x gcc9 (9.2.1). All the log is [here](https://gist.github.com/junaruga/ea2956f59189d554281541853c0f5843).

**Comment by nemequ** [comment] 2020-03-30 22:04
Hm, that's going to be tricky to reproduce.  Since you were trying to build on gcc 10 the other day, do you happen to know if gcc 10 on s390x works?  If it's still happening I'd like to report it to the GCC folks ASAP.

I'll try to get an s390x VM going.

**Comment by nemequ** [comment] 2020-03-30 22:23
gcc 10 on x86 should be fixed: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94385

I'll keep this open for the s390x issue, which I'm going to try to get to right after that ppc64le issue.

**Comment by nemequ** [comment] 2020-04-01 06:38
I'm having trouble getting an s390x VM going; F31 netinst failed horribly, F31 & F32 dvd both seemed to work but wouldn't boot into the new system.  I'm going to try to figure something else out (maybe use qemu directly instead of virt-manager), but in the meantime…

I'm not sure what to do about GCC 9, but since the problem seems to be with the `__builtin_convertvector` inside of a statement expr I was thinking about this for GCC 10:

```diff
diff --git a/simde/simde-common.h b/simde/simde-common.h
index 78df1d1..e023b2d 100644
--- a/simde/simde-common.h
+++ b/simde/simde-common.h
@@ -160,12 +160,16 @@
    but the code needs to be refactored a bit to take advantage. */
 #  if !defined(SIMDE_NO_CONVERT_VECTOR) && defined(SIMDE_VECTOR_SUBSCRIPT)
 #    if HEDLEY_HAS_BUILTIN(__builtin_convertvector) || HEDLEY_GCC_VERSION_CHECK(9,0,0)
-/* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93557 */
-#      define SIMDE__CONVERT_VECTOR(to, from) ((to) = (__extension__({ \
-           __typeof__(from) from_ = (from); \
-           ((void) from_); \
-           __builtin_convertvector(from_, __typeof__(to)); \
-         })))
+#      if HEDLEY_GCC_VERSION_CHECK(9,0,0) && !HEDLEY_GCC_VERSION_CHECK(9,3,0)
+         /* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=93557 */
+#        define SIMDE__CONVERT_VECTOR(to, from) ((to) = (__extension__({ \
+             __typeof__(from) from_ = (from); \
+             ((void) from_); \
+             __builtin_convertvector(from_, __typeof__(to)); \
+           })))
+#      else
+#        define SIMDE__CONVERT_VECTOR(to, from) ((to) = __builtin_convertvector((from), __typeof__(to)))
+#      endif
 #    endif
 #  endif
 #endif
```

Does that seem reasonable to you?

**Comment by junaruga** [comment] 2020-04-03 21:32
> Hm, that's going to be tricky to reproduce. Since you were trying to build on gcc 10 the other day, do you happen to know if gcc 10 on s390x works? If it's still happening I'd like to report it to the GCC folks ASAP.

Yes, simde works with gcc 10 on s390x on Fedora 33 (= rawhide). Thanks for the report!

> Does that seem reasonable to you?

Thanks for the investigation and the patch! Let me check it.
If we can use https://packit.dev/packit-as-a-service/ , we might be able to build simde at the pull-request timing on native Fedora NN environments. I take a look at it.

**Comment by junaruga** [comment] 2020-04-04 20:23
> I faced the same kind of error on Fedora 31 s390x gcc9 (9.2.1).

> Thanks for the investigation and the patch! Let me check it.

I conformed your patch works on the Fedora 31 s390x gcc9, though Fedora 31 and 30's gcc was upgraded to 9.3.1 now. There is not way to check it on gcc-9.2.1.
Thanks!

A good news is now I succeeded to build and run the unit tests on Fedora [rawhide( = 33)](https://koji.fedoraproject.org/koji/taskinfo?taskID=43023130), [32](https://koji.fedoraproject.org/koji/taskinfo?taskID=43023314), [31](https://koji.fedoraproject.org/koji/taskinfo?taskID=43023329), [30](https://koji.fedoraproject.org/koji/taskinfo?taskID=43023337).
I will try to run the unit tests with some compiler flags as a further test.

**Comment by junaruga** [comment] 2020-04-04 20:33
Feel free to close this ticket. Thanks.

**Comment by nemequ** [comment] 2020-04-04 20:37
The patch is running through CI right now as 2285554b7a1608520782139503cc1d52cbada974.  Interestingly I'm just waiting for the s390x build, but as soon as it's done I'll merge it into master.

**Closed by nemequ** 2020-04-04 20:37 UTC
