### ISSUE TITLE
Handling of NaNs and differences between SSE and NEON

### ISSUE THREAD

**Issue by ngzhian** [nemequ/simde#291] opened 2020-05-14 00:16 UTC
Looking at https://github.com/nemequ/simde/blob/master/simde/x86/sse.h#L2203 it looks like minps on x86 is directly mapped to vminq_f32 on arm. However these two instructions have different behavior.

```
minps(NaN, 0.0) = 0.0
vmin(NaN, 0.0) = default NaN
```

Is this considered a bug? What are the expectations for such cases?

Thanks!

**Comment by nemequ** [comment] 2020-05-14 05:49
Frankly, I've been pretty lax about this.

I think most people don't really worry too much about NaN, treating them almost like undefined behavior.  The vast majority of code I've seen smply doesn't really deal with NaNs, or deals with them by avoiding them.

For the vast majority of code I'm not sure it's worth the overhead to check for NaNs and reproduce the Intel API's behavior exactly.  That said, I'd certainly be open to allowing people to opt in to more faithful NaN handling.  Maybe by defining a preprocessor macro before including SIMDe (`SIMDE_FAITHFUL_NANS`?), or possibly even calling a different function (e.g., `simde_nan_mm_min_ps` instead of `simde_mm_min_ps`, or some other name)?

For example, in this case I think you'd need a couple of `vceqq_f32`s to check for NaNs, plus the `vminq_f32`, then you'd have to blend everything together.  That's a pretty big performance hit, and I suspect the percentage of code that would benefit from it is vanishingly small.  If we could do it more efficiently I'd be much more interested.

I'm definitely open to having my mind changed here. Are you actually havinge a problem with this, or just bringing up somethnig you noticed?

I should definitely document this somewhere…

**Comment by ngzhian** [comment] 2020-05-14 16:31
Thanks for the detailed response!

> 
> For example, in this case I think you'd need a couple of `vceqq_f32`s to check for NaNs, plus the `vminq_f32`, then you'd have to blend everything together. That's a pretty big performance hit, and I suspect the percentage of code that would benefit from it is vanishingly small. If we could do it more efficiently I'd be much more interested.

Agree that in most cases it wouldn't be noticeable, and in order to faithfully replicate behavior it would be require many more instructions and be a lot slower.

> 
> I'm definitely open to having my mind changed here. Are you actually havinge a problem with this, or just bringing up somethnig you noticed?

This came about as we were thinking of #76 . WebAssembly aims to be portable and deterministic, so it's important that we get the same results on all architectures. And so when we were looking at SIMDe from this angle, a co-worker noticed this difference in NaN handling.

Thus, when implementing WebAssembly functions, we will need to ensure the same behavior (even without the hypothetical SIMDE_FAITHFUL_NANS), i.e. a wasm_f32x4_min cannot be simply lowered to minps. [(zeux/wasm-simd](https://github.com/zeux/wasm-simd/blob/master/Instructions.md) nicely documents the instruction sequence difference for various Wasm instructions, particularly see f32x4 or f64x2 instructions which map directly to a single ARM instruction, but requires more work on x86).

> 
> I should definitely document this somewhere…

Yea! I think it would be nice to point this out in the README, with this issue linked as an example? It would be tiring to try and list it out exhaustively :)

**Comment by nemequ** [comment] 2020-05-15 05:10
Maybe it would be more appropriate to invert the logic, and instead have people define `SIMDE_UNFAITHFUL_NANS` (or likely something else, I haven't really thought about the name at all)?  Safe defaults with an opt-in to sacrifice compatibility for speed (kind of like `-ffast-math`) is probably better than unsafe-by-default.

TBH, I was thinking about this more from the perspective of getting existing SSE/AVX code to run fast on other CPUs, which I think is going to be the common case for the Intel implementations.  

However, for other architectures (including WebAssembly) using SIMDe to make it easier to write software targeting that architecture is a very important use case.  I know I'd love to be able to develop WASM, NEON, POWER, etc. code on my x86 desktop without an emulator, interpreter, cross-compiler, etc.  That's actually one of the main use cases for SIMDe, and for that case I think safe by default makes a lot of sense.

I don't think it would be particularly difficult to start adding NaN test cases to eliminate this type of issue, though it would be rather time-consuming.

Thanks for bringing this up.  Obviously I haven't spent nearly enough time thinking about this issue :/

**Comment by ngzhian** [comment] 2020-05-15 20:53
> Maybe it would be more appropriate to invert the logic, and instead have people define `SIMDE_UNFAITHFUL_NANS` (or likely something else, I haven't really thought about the name at all)? Safe defaults with an opt-in to sacrifice compatibility for speed (kind of like `-ffast-math`) is probably better than unsafe-by-default.

`SIMDE_UNFAITHFUL_NANS` sounds like a great band name :)
It does seem more natural to follow what gcc/clang does with `-ffast-math` - correctness by default, and opt-int to speed (which sacrifices accuracy)

> I don't think it would be particularly difficult to start adding NaN test cases to eliminate this type of issue, though it would be rather time-consuming.

Yea agree, there is a manageable pair of "interesting" constants we will want to test for:
- -0.0, 0.0
- 0.0, -0.0
- qNaN, 1.0
- 1.0, qNaN
- sNaN, 1.0
- 1.0, sNaN

This *should* be sufficient to uncover a lot of differences

> Thanks for bringing this up. Obviously I haven't spent nearly enough time thinking about this issue :/

Ofc, no problem at all. Thanks for your thoughtful response, it's great to hear about your motivation, and how responsive you are to our feedback. And credit to @Maratyszcza for noticing these differences.

**Comment by nemequ** [comment] 2020-06-08 07:19
Okay, this is finally fixed in master (with 1957409d941998d97221bc91b76ca7cf12398b8d), sorry it took so long.

`_mm_min_ps` was actually substantially simpler than I'd feared; it doesn't treat NaNs as < normal numbers, it really behaves like `(a < b) ? a : b`.  (NaN, normal) returns normal, and (normal, NaN) returns NaN.  I just used `vcmpltq_f32` (plus a couple masks), so it's faster than I was expecting.

For the unfaithful NaNs stuff, I went with `SIMDE_FAST_NANS`.  I also noticed that GCC and clang define `__FINITE_MATH_ONLY__` to `1` if you use `-ffinite-math-only`, which is included in `-ffast-math`.  Since it does exactly the same thing as `SIMDE_FAST_NANS` I went ahead and defined `SIMDE_FAST_NANS` if `__FINITE_MATH_ONLY__ == 1`, unless you override that by defining `SIMDE_NO_FAST_NANS`.

I also added a few other `SIMDE_FAST_*` settings, one for the rounding mode and one for how to round ties, but neither actually does anything yet.

Defining `SIMDE_FAST_MATH` (or passing `-ffast-math` to the compiler) enables all the `SIMDE_FAST_*` options, but I might take `SIMDE_FAST_ROUND_MODE` out of that and require the user to explicitly define it.  IMHO `SIMDE_FAST_ROUND_TIES` definitely makes sense, though.

**Closed by nemequ** 2020-06-08 07:19 UTC
